### ISSUE TITLE
bug: Replace mongodb to mongoose

### ISSUE THREAD

**Issue by akshatnema** [akshatnema/jobie#6]
### Describe the bug
The current server implementation contains `mongodb` node package to connect to the database, which is slightly unstable during repeated fetch calls. MongoClient gets disconnected very soon during the fetch requests.

### How to Reproduce
Steps to reproduce the issue:
- Make repeated calls to `/` route to produce an error on server console.

### Screenshots
![Screenshot from 2022-07-24 12-56-52](https://user-images.githubusercontent.com/76521428/180638324-d1f78fa2-54fc-418a-9340-f8bea6a4683f.png)

### Expected behavior
Want a continuous and uninterrupted response of fetch requests without getting any error using `mongoose`.

**Comment by shamoon1997** [comment]
I am doing

**Comment by akshatnema** [comment]
Thanks, @shamoon1997. If you get any error in setting this repo in development mode, do let me know. I'll help you.

**Comment by shamoon1997** [comment]
Yes Please I need the .env to run it 

<img width="1433" alt="image" src="https://user-images.githubusercontent.com/49757455/180760346-63274d0a-5a63-4e13-b918-4fbb8734bd9a.png">

**Comment by akshatnema** [comment]
> Yes Please I need the .env to run it

I can't give you the production level environment variables for development mode. What you can do is make a sample Mongodb cluster+database from your account and test the functionality with it. For twitter bearer token, use this:

```AAAAAAAAAAAAAAAAAAAAANAUSgEAAAAA%2BwvPQqv%2BVJjGFlAZNiktyzNP7F4%3DRZUMIviTyDIqPvl31g6iyXK6mh8YegA8Wgvmvs3rdCH93sdrzv```

Remember, this is not a production Twitter Bearer token so you need to add rules to the token using curl commands to test the functionality of addition of tweets to the database automatically. For reference, you can visit the page - https://akshat-google-cloud.notion.site/Twitter-API-data-9e013026a2ae452b9a5ed57660ec6f5b

**Comment by akshatnema** [comment]
@shamoon1997 are you able to set up the repo and work on this issue?
