### ISSUE TITLE
[📑 Docs]: Add proper README and CONTRIBUTING.md files

### ISSUE THREAD

**Issue by akshatnema** [akshatnema/jobie#8]
Improve the README of this repository by adding proper tags and `Steps to contribute` to this project. Also, add a CONTRIBUTING.md file to list down all the requirements required and the guidelines to follow while contributing to this project.

**Comment by Dun-sin** [comment]
Can i help with this?

**Comment by akshatnema** [comment]
Hey @Dun-sin thanks for showing interest in the project. Sorry, right now, we're allowing our college mates to contribute to this project and help them in getting knowledge of open source software and development. So, most probably, one of my college mates will take up this issue.

Thanks!!

**Comment by Priyansh61** [comment]
hey 
Can you assign me to this issue ??

**Comment by akshatnema** [comment]
Hey @Priyansh61, go on :rocket:

**Comment by Dun-sin** [comment]
> Hey @Dun-sin thanks for showing interest in the project. Sorry, right now, we're allowing our college mates to contribute to this project and help them in getting knowledge of open source software and development. So, most probably, one of my college mates will take up this issue.
> 
> Thanks!!

Awesome, maybe say that in your README, so people outside your college don't contribute here

**Comment by akshatnema** [comment]
> Awesome, maybe say that in your README, so people outside your college don't contribute here

Yeah sure. Note this down @Priyansh61

**Comment by Priyansh61** [comment]
Ok will upload a temporary readme file for now stating the given information
